server:
  port: 8099

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: 118.24.62.144
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#spring:
#  profiles:
#    active: peer1,peer2

#java -jar eurekaserver-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer1
#java -jar eurekaserver-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer2