eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/,http://localhost:8869/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign